export default {
    user: {
        username: "",
        email: ""
    },
    business: [
        {
            "id": 1,
            "name": 'Wilder Wood',
            "description": '100% Gluten-free restaurant serving American fare with two bars, a rooftop patio & great views.',
            "address": '1300 E 7th St, Austin, TX 78702',
            "phone": '(512) 628-0184',
            "hours": '10AM - 10PM'
        },
        {
            "id": 2,
            "name": 'Picnik',
            "description": 'Modern cafe accommodating paleo, veggie & gluten-free plus bone broth, wine, beer & coffee.',
            "address": '4801 Burnet Rd, Austin, TX 78756',
            "phone": '(737) 226-0644',
            "hours": '8AM - 8PM',
        },
        {
            "id": 3,
            "name": 'Counter Culture',
            "description": 'Innovative vegan fare (plus beer & wine) served in a blue-walled dining room or on an outdoor patio.',
            "address": '2337 E Cesar Chavez St, Austin, TX 78702',
            "phone": '(512) 524-1540',
            "hours": '11AM - 10PM',
        },
        {
            "id": 4,
            "name": 'Juliet Italian Kitchen',
            "description": 'Modern & classic Italian fare & drinks in a spacious, multiroom setting with luxe flourishes.',
            "address": '1500 Barton Springs Rd, Austin, TX 78704',
            "phone": '(512) 479-1800',
            "hours": '11:30 - 9PM',
        },
        {
            "id": 5,
            "name": 'Taverna',
            "description": 'Casual Italian chainlet featuring pizzas, risottos & sidewalk seating.',
            "address": '258 W 2nd St, Austin, TX 78701',
            "phone": '(512) 477-1001',
            "hours": '10AM - 2AM',
        },
        {
            "id": 6,
            "name": 'Thai Fresh',
            "description": 'Cooked-to-order dishes & homemade ice creams, plus market with hard-to-find Thai ingredients.',
            "address": '909 W Mary St, Austin, TX 78704',
            "phone": '(512) 494-6436',
            "hours": '9AM - 9PM',
        },
        {
            "id": 7,
            "name": 'Snooze, an A.M. Eatery',
            "description": 'Vibrant, retro chain serving a seasonal menu of creative breakfast & lunch fare, plus cocktails.',
            "address": '1700 S Lamar Blvd Suite 301, Austin, TX 78704',
            "phone": '(512) 428-8444',
            "hours": '6:30AM - 2:30PM',
        },
        {
            "id": 8,
            "name": 'True Food Kitchen',
            "description": 'Relaxed, eco-chic chain serving health-conscious fare, including vegan options, plus cocktails.',
            "address": '222 West Ave Ste HR100, Austin, TX 78701',
            "phone": '(512) 777-2430',
            "hours": '11AM - 9PM',
        },
        {
            "id": 9,
            "name": 'Koriente',
            "description": 'Pan-Asian fare, including vegan & gluten-free options, in a homey, easygoing eatery with a patio.',
            "address": '621 E 7th St, Austin, TX 78701',
            "phone": '(512) 275-0852',
            "hours": '11AM - 9:30PM',
        },
        {
            "id": 10,
            "name": 'Zucchini Kill Bakery',
            "description": 'Punk rock, female-led bakery serving vegan sweet & savory goods that are also soy & gluten-free.',
            "address": '701 E 53rd St Suite C, Austin, TX 78751',
            "phone": '(737) 215-5936',
            "hours": '10AM - 4PM',
        },
        {
            "id": 11,
            "name": 'Mr. Natural',
            "description": 'Mexican-focused vegetarian quick-serve eatery with a health food shop, bakery & juice bar.',
            "address": '2414A S Lamar Blvd, Austin, TX 78704',
            "phone": '(512) 916-9223',
            "hours": '2:30PM - 9PM',
        },
        {
            "id": 12,
            "name": 'Intero Restaurant',
            "description": 'Sustainability focused farm-to-table Italian with pasta & artisanal chocolate on a rotational menu.',
            "address": '2612 E Cesar Chavez St Suite 105, Austin, TX 78702',
            "phone": '(512) 599-4052',
            "hours": '5PM - 9PM',
        },
        {
            "id": 13,
            "name": 'East Side Pies',
            "description": 'Offbeat toppings, plus Chicago-style & gluten-free pies, keep this pizza chain outpost hopping.',
            "address": '1401 Rosewood Ave, Austin, TX 78702',
            "phone": '(512) 524-0933',
            "hours": '10AM - 10PM',
        },
        {
            "id": 14,
            "name": 'Citizen Eatery',
            "description": 'Bright, health-conscious cafe & full bar serving a 100% meat-free menu including all-day breakfast.',
            "address": '5011 Burnet Rd, Austin, TX 78756',
            "phone": '(512) 792-9546',
            "hours": '10AM - 9PM',
        },
        {
            "id": 15,
            "name": 'Snap Kitchen',
            "description": 'Local grab-&-go chain specializing in health-focused takeaway meals, juices & snacks.',
            "address": '1014 W 6th St, Austin, TX 78703',
            "phone": '(512) 479-5959',
            "hours": '8AM - 7PM',
        },
        {
            "id": 16,
            "name": 'Modern Market Eatery',
            "description": 'Counter-serve cafe with salads, sandwiches, pizzas including both vegan & vegetarian options.',
            "address": '401 Congress Ave, Austin, TX 78701',
            "phone": '(512) 666-3099',
            "hours": '10AM - 9PM',
        },
        {
            "id": 17,
            "name": 'Curcuma',
            "description": 'Health-forward 100% plant-based food trailer serving Ayruvedic menu',
            "address": '2324 E Cesar Chavez St, Austin, TX 78702',
            "phone": '(512) 956-9550',
            "hours": 'Temporarily Closed',
        },
        {
            "id": 20,
            "name": 'Next Level Burger',
            "description": 'Dine-in, Takeout, and No-Contact Delivery. Also available via Grubhub',
            "address": '525 N Lamar Blvd, Austin, TX 78703',
            "phone": '(737) 212-0411',
            "hours": '11AM - 9PM',
        },
        {
            "id": 21,
            "name": 'Red Robin Gourmet Burgers and Brews',
            "description": 'Chain for gourmet burgers & other American comfort fare.',
            "address": '5601 Brodie Ln, Sunset Valley, TX 78745',
            "phone": '(512) 277-2220',
            "hours": '11AM - 9PM',
        },
        {
            "id": 22,
            "name": "Austin's Pizza South Lamar",
            "description": 'Take-out & delivery-focused chain serving pizza until late-night with gluten-free & vegan options.',
            "address": '1817 S Lamar Blvd, Austin, TX 78704',
            "phone": '(512) 717-8764',
            "hours": '11AM - 10PM',
        },
        {
            "id": 23,
            "name": 'Spartan Pizza',
            "description": 'NYC-style specialty pizza, plus sandwiches & salads, served in a natural light-filled location.',
            "address": '1007 E 6th St, Austin, TX 78702',
            "phone": '(512) 484-0798',
            "hours": '11AM - 10PM',
        },
        {
            "id": 24,
            "name": 'Intero Restaurant',
            "description": 'Sustainability focused farm-to-table Italian with pasta & artisanal chocolate on a rotational menu.',
            "address": '2612 E Cesar Chavez St Suite 105, Austin, TX 78702',
            "phone": '(512) 599-4052',
            "hours": '5PM - 9PM',
        },
        {
            "id": 25,
            "name": 'North Italia',
            "description": 'Buzzy, modern Italian option with a patio for thin-crust pizzas & sophisticated Italian fare.',
            "address": '500 W 2nd St #120, Austin, TX 78701',
            "phone": '(512) 777-5062',
            "hours": '11AM - 10PM',
        },
    ]
};